databases:
  - name: postgres
    ipAllowList: []
    databaseName: recipe_app_production
    user: recipe_app

services:
  - type: web
    name: recipe_app
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false